import 'package:tool_core_app/l10n/app_localizations.dart';

import 'api_exception.dart';

/// Maps an error code to a localized message.
String localizeErrorCode(AppLocalizations l10n, String code) {
  switch (code) {
    case 'invalid-credentials':
      return l10n.errorInvalidCredentials;
    case 'validation-error':
      return l10n.errorValidation;
    case 'work-order-not-found':
      return l10n.errorWorkOrderNotFound;
    case 'work-order-status-not-found':
      return l10n.errorWorkOrderStatusNotFound;
    case 'work-order-transition-invalid':
      return l10n.errorWorkOrderTransitionInvalid;
    case 'work-order-locked':
      return l10n.errorWorkOrderLocked;
    case 'work-order-line-not-found':
      return l10n.errorWorkOrderLineNotFound;
    case 'work-order-vehicle-required':
      return l10n.errorWorkOrderVehicleRequired;
    case 'line-quantity-invalid':
      return l10n.errorLineQuantityInvalid;
    case 'line-price-invalid':
      return l10n.errorLinePriceInvalid;
    case 'line-hours-invalid':
      return l10n.errorLineHoursInvalid;
    case 'labor-description-required':
      return l10n.errorLaborDescriptionRequired;
    case 'discount-invalid':
      return l10n.errorDiscountInvalid;
    case 'mechanic-not-found':
      return l10n.errorMechanicNotFound;
    case 'payment-amount-invalid':
      return l10n.errorPaymentAmountInvalid;
    case 'payment-method-invalid':
      return l10n.errorPaymentMethodInvalid;
    case 'payment-exceeds-balance':
      return l10n.errorPaymentExceedsBalance;
    case 'document-type-required':
      return l10n.errorDocumentTypeRequired;
    case 'customer-not-found':
      return l10n.errorCustomerNotFound;
    case 'customer-first-name-required':
      return l10n.errorCustomerFirstNameRequired;
    case 'customer-required':
      return l10n.errorCustomerRequired;
    case 'vehicle-not-found':
      return l10n.errorVehicleNotFound;
    case 'vehicle-plate-required':
      return l10n.errorVehiclePlateRequired;
    case 'vehicle-plate-already-exists':
      return l10n.errorVehiclePlateExists;
    case 'vehicle-brand-required':
      return l10n.errorVehicleBrandRequired;
    case 'vehicle-model-required':
      return l10n.errorVehicleModelRequired;
    case 'vehicle-year-invalid':
      return l10n.errorVehicleYearInvalid;
    case 'vehicle-mileage-invalid':
      return l10n.errorVehicleMileageInvalid;
    case 'product-not-found':
      return l10n.errorProductNotFound;
    case 'product-name-required':
      return l10n.errorProductNameRequired;
    case 'product-price-invalid':
      return l10n.errorProductPriceInvalid;
    case 'product-category-required':
      return l10n.errorProductCategoryRequired;
    case 'product-category-not-found':
      return l10n.errorProductCategoryNotFound;
    case 'product-not-in-workshop':
      return l10n.errorProductNotInWorkshop;
    case 'product-unit-invalid':
      return l10n.errorProductUnitInvalid;
    case 'barcode-already-exists':
      return l10n.errorBarcodeExists;
    case 'movement-type-invalid':
      return l10n.errorMovementTypeInvalid;
    case 'movement-quantity-invalid':
      return l10n.errorMovementQuantityInvalid;
    case 'insufficient-stock':
      return l10n.errorInsufficientStock;
    case 'service-not-found':
      return l10n.errorServiceNotFound;
    case 'service-name-required':
      return l10n.errorServiceNameRequired;
    case 'service-price-invalid':
      return l10n.errorServicePriceInvalid;
    case ClientErrorCodes.workshopNotSelected:
      return l10n.errorWorkshopNotSelected;
    case ClientErrorCodes.network:
      return l10n.errorNetwork;
    case ClientErrorCodes.tooManyRequests:
      return l10n.errorTooManyRequests;
    case ClientErrorCodes.sessionExpired:
      return l10n.errorSessionExpired;
    default:
      return l10n.errorUnexpected;
  }
}
